INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', '1,2 Dicloroetano', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', '2 - Clorofenol', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', '2,4 - D', '', '', 720.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', '2,4 Diclorofenol', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', '2,4,5-TP', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', '2,4,6 Triclorofenol', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', '3,3-Diclorobenzidina', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Acidez', '', '', 10.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Acrilamida', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Alaclor', '', '', 720.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Alcalinidade CO3', '', '', 5.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Alcalinidade HCO3', '', '', 5.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Alcalinidade OH', '', '', 5.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Alcalinidade Total', '', '', 15.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Aldrin + Dieldrin', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Alumínio', '', '', 12.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Alumínio dissolvido', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Amônia', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Amoníaco', '', '', 12.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Amônio', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Antimônio', '', '', 28.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Antrazina', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Areia', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Argila', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Arsênio total', '', '', 20.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Aspecto', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Aspergillus niger', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Atrazina', '', '', 720.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Bacillus cereus', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Bactérias Heterotróficas', '', '', 10.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Bário total', '', '', 12.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Bentazona', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Benzeno', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Benzeno-a-antraceno', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Benzeno-a-Pireno', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Benzeno-b-Fluoranteno', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Benzeno-k-Fluoranteno', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Benzidina', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Benzo[a]pireno', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Berílio total', '', '', 18.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Bolores e Leveduras', '', '', 20.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Boro total', '', '', 12.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Bromato', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'C.T.C', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Cádmio total', '', '', 12.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Cálcio e Magnésio', '', '', 25.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Cálcio total', '', '', 15.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Candida albicans', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Carbaril', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Carbono', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Centrifugação', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Chumbo total', '', '', 12.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Cianobactérias', '', '', 120.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Cianotoxinas', '', '', 110.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Cianeto livre', '', '', 15.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Cianeto total', '', '', 15.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Clordano (cis + trans)', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Clordano (isômeros)', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Cloreto de Vinila', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Cloreto total', '', '', 20.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Clorito', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Cloro residual Livre', '', '', 20.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Cloro residual total', '', '', 20.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Clorofila “a”', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Clorofórmio', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Clostrídio sulfito redutor à 46°C', '', '', 40.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Clostrídio Sulfito Redutores ou Clostridium perfrigens', '', '', 50.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Cobalto total', '', '', 12.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Cobre dissolvido', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Cobre total', '', '', 12.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Coliformes fecais', '', '', 10.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Coliformes Termotolerantes', '', '', 10.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Coliformes Totais', '', '', 10.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Condutividade a 25°C', '', '', 5.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Contagem de Bactérias Heterotróficas', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Contagem de Coliformes Termotolerantes à 45°C', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Contagem de Coliformes Totais', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Contagem de microrganismos viáveis totais', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Contagem padrão em placa', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Contagem Total de Bolores e Leveduras', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Cor', '', '', 5.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Cor aparente', '', '', 5.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Cor Verdadeira', '', '', 5.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Corantes Artificiais', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Criseno', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Cromo hexavalente', '', '', 15.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Cromo total', '', '', 15.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Cromo trivalente', '', '', 15.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'CTC', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'DBO 5 a 20°C', '', '', 45.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'DDT (isômeros)', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'DDT (p,p”-DDT+p,p’-DDE + p,p’ –DDD)', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Demeton (Demeton-O + Demeton-S)', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Densidade', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Densidade de Cianobactérias', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Descrição', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Dibenzo (a,h) antraceno', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Dicloroeteno', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Diclorometano', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Dióxido de Carbono', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Dodecacloro pentaciclodecano', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'DQO', '', '', 45.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Dureza total', '', '', 10.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Detecção de ovos de Helmintos', '', '', 35.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Eber', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Endossulfan', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Endossulfan (a+b+sulfato)', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Endrin', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Enexofre', '', '', 15.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Enterococcus sp', '', '', 20.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Enxofre total', '', '', 15.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Escherichia Coli', '', '', 80.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Escherichia coli ou Coliformes Termotolerantes', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Estafilococos coagulase positiva', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Estanho total', '', '', 13.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Estireno', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Etilbenzeno', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Extrato Etéreo', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Fenóis totais', '', '', 45.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Ferro', '', '', 15.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Ferro dissolvido', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Ferro solúvel', '', '', 12.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Fluoreto total', '', '', 20.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Fosfato', '', '', 20.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Fósforo (resina)', '', '', 20.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Fósforo total', '', '', 32.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Gás Sufídrico', '', '', 20.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Glifosato', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Gosto', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'H + Al', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Heptacloro e Heptacloro epóxido', '', '', 720.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Hexaclorobenzeno', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'IVL - Índice Volumétrico de Lodo', '', '', 20.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Klebsiella pneumonease', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Limo', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Lindano', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Lítio total', '', '', 15.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'M.Orgân.', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Magnésio total', '', '', 10.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Manganês dissolvido', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Manganês total', '', '', 12.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Matéria Mineral', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Matéria orgânica', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Matéria Seca', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Materiais Flutuantes', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Mercúrio total', '', '', 90.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Metolacloro', '', '', 720.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Metoxicloro', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Microscopia de lodos ativados - parcial', '', '', 150.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Microscopia de lodos ativados - completa', '', '', 280.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Microcistinas', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Microrganismos Mesófilos Totais Aeróbios 35°C/ 72h', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Molibdênio', '', '', 12.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Molinato', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Monocloramina', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Monoclorobenzeno', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Níquel total', '', '', 15.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Nitratos ', '', '', 20.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Nitritos', '', '', 20.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Nitrogênio amoniacal', '', '', 22.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Nitrogênio amoniacal total', '', '', 22.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Nitrogênio de Kjeldahl', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Nitrogênio de Nitrato', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Nitrogênio de Nitrito', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Nitrogênio orgânico', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Nitrogênio total', '', '', 37.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Odor', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Óleos e Graxas', '', '', 45.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Organo fosforado  + Carbamatos', '', '', 720.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Ortofosfato', '', '', 20.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Oxigênio consumido', '', '', 20.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Oxigênio Dissolvido', '', '', 20.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Pendimetalina', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Pentaclorofenol', '', '', 720.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Permetrina', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Peróxido', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Pesquisa de Salmonella sp', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'pH a 25°C', '', '', 10.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Potássio total', '', '', 15.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Prata total', '', '', 10.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Propanil', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Proteína Bruta', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Pseudomonas aeruginosa', '', '', 20.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Radioatividade Alfa ', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Radioatividade Beta  ', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Regime de lançamento', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Resíduo de evaporação', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Salmonella sp ', '', '', 15.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Sat.Base', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Selênio total', '', '', 31,5.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Sílica', '', '', 20.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Silício', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Silte', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Simazina', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Sólidos dissolvidos fixos', '', '', 15.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Sólidos dissolvidos totais', '', '', 15.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Sólidos dissolvidos voláteis', '', '', 15.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Sólidos sedimentáveis', '', '', 10.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Sólidos suspensos fixos / não filtrantes', '', '', 15.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Sólidos suspensos totais', '', '', 20.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Sólidos suspensos voláteis', '', '', 15.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Sólidos totais', '', '', 15.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Sólidos totais fixos', '', '', 15.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Sólidos totais voláteis', '', '', 15.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Staphylococcus aureus', '', '', 10.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Staphylococcus sp', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Substâncias Oxidáveis', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Substâncias que comunicam cor ou odor', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Sulfato total', '', '', 20.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Sulfatos', '', '', 20.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Sulfeto (H2S não dissociado)', '', '', 20.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Sulfeto de Hidrogênio', '', '', 20.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Sulfetos', '', '', 20.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Sulfitos', '', '', 28.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Surfactantes', '', '', 30.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'SWAB em superfície', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Temperatura', '', '', 5.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Tetracloreto de Carbono', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Tetracloroeteno', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Tolueno', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Toxafeno', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Tributilestanho', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Tricloreteno', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Triclorobenzeno (1,2,3-TCB + 1,2,4 – TCB)', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Triclorobenzenos', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Tricloroeteno', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Trifluralina', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Trihalometanos Total', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Turbidez', '', '', 10.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Umidade', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Urânio', '', '', 280.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Vanádio total', '', '', 30.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Viscosidade', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Xileno', '', '', 0.00);
INSERT INTO parametro (id, lq, ld, nome, metodo, unidadeMedida, preco) VALUES (default, '', '', 'Zinco total', '', '', 12.00);
COMMIT;